# config.yaml
rpc_connection: "http://127.0.0.1:8899"
ws_connection: "ws://127.0.0.1:8900"
redis_password: "corvus8redis2"
redis_hostname: "localhost"
redis_port: "16679"
private_key: "4nZBu4UV8XttX18nzZbv5yjfb28nkavKXMFYnWAFPBg4Bs4LPksQsLFLxVnkyaZQTQMMtd2zfZ9gZ9GqLCUfoHhF"
jito_bundle_endpoint: "https://ny.mainnet.block-engine.jito.wtf/api/v1/bundles"
jito_tx_endpoint: "https://ny.mainnet.block-engine.jito.wtf/api/v1/transaction"
bloxroute_endpoint: "https://bloxroute-endpoint-url.com"
bloxroute_auth_header: "ZDEwZDI1NDYtMzBmNS00MjAwLWExZTctY2I3NmZjYWUxYmI5OmQ0OTViYjgwMzFmZDhjMTMxMWRlNzkxMWNjOTk1MWRm"
bloxroute_tip_address: "95cfoy472fcQHaw4tPGBTKpn6ZQnfEPfBgDQx6gcRmRg"
helius_api_key: "1ea7f7e7-925d-43a6-a3bc-3caf2be4551e"
helius_rpc: "https://mainnet.helius-rpc.com/?api-key=1ea7f7e7-925d-43a6-a3bc-3caf2be4551e"
helius_staked_rpc: "https://staked.helius-rpc.com/?api-key=1ea7f7e7-925d-43a6-a3bc-3caf2be4551e"
mainnet_endpoint: "https://api.mainnet-beta.solana.com"
lamports_per_sol: "1000000000"
wsol_address: "So11111111111111111111111111111111111111112"
usdc_address: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
raydium_amm_program_id: "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8"
raydium_clmm_program_id: "CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK"